name: Ubuntu 22.04 DXFImportPlugin

on:
  # run nightly at 2:00 am

  # allow to be triggered on github webpage manually
  workflow_dispatch:
  # run whenever someone pushes data
  # WARNING: this may give excessive build times which need to be paid!
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    # Test suite results are created on Ubuntu 22.04, hence we need to use this for testing
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: build
      working-directory: build/cmake
      run: ./build.sh 2 release
